### ISSUE TITLE
init mode failed (unable to connect to the target)

### ISSUE THREAD

**Issue by Hermit12** [ddavidebor/nRF51822-OSX-ST_LINK_V2-Flasher-Script#2]
Hi there, 
thank you for your work. I am currently unable to connect to the target, do you have any idea what can cause this issue?

Thank you

`Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 1000 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : Unable to match requested speed 1000 kHz, using 950 kHz
Info : clock speed 950 kHz
Info : STLINK v2 JTAG v17 API v2 SWIM v4 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 3.540158
Error: init mode failed (unable to connect to the target)
in procedure 'init' 
in procedure 'ocd_bouncer'`

**Comment by ddavidebor** [comment]
Hello,
Sorry about the lack of a reply.
Did you solve it?
David

**Comment by Joker-Jick** [comment]
Hello，
I also met the problem and hadn`t find the way to solve it.
Could you please give me a hand?
Jack

**Comment by ddavidebor** [comment]
Hi, I think the issue is simply it's not wired properly. Can't help you much, this was ages ago.
